/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProductRouteImport } from './routes/product'
import { Route as HumanRouteImport } from './routes/human'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductIndexRouteImport } from './routes/product.index'
import { Route as HumanIndexRouteImport } from './routes/human.index'
import { Route as ProductCvRouteImport } from './routes/product.cv'
import { Route as HumanMusicRouteImport } from './routes/human.music'
import { Route as HumanHobbiesRouteImport } from './routes/human.hobbies'

const ProductRoute = ProductRouteImport.update({
  id: '/product',
  path: '/product',
  getParentRoute: () => rootRouteImport,
} as any)
const HumanRoute = HumanRouteImport.update({
  id: '/human',
  path: '/human',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIndexRoute = ProductIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProductRoute,
} as any)
const HumanIndexRoute = HumanIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HumanRoute,
} as any)
const ProductCvRoute = ProductCvRouteImport.update({
  id: '/cv',
  path: '/cv',
  getParentRoute: () => ProductRoute,
} as any)
const HumanMusicRoute = HumanMusicRouteImport.update({
  id: '/music',
  path: '/music',
  getParentRoute: () => HumanRoute,
} as any)
const HumanHobbiesRoute = HumanHobbiesRouteImport.update({
  id: '/hobbies',
  path: '/hobbies',
  getParentRoute: () => HumanRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/human': typeof HumanRouteWithChildren
  '/product': typeof ProductRouteWithChildren
  '/human/hobbies': typeof HumanHobbiesRoute
  '/human/music': typeof HumanMusicRoute
  '/product/cv': typeof ProductCvRoute
  '/human/': typeof HumanIndexRoute
  '/product/': typeof ProductIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/human/hobbies': typeof HumanHobbiesRoute
  '/human/music': typeof HumanMusicRoute
  '/product/cv': typeof ProductCvRoute
  '/human': typeof HumanIndexRoute
  '/product': typeof ProductIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/human': typeof HumanRouteWithChildren
  '/product': typeof ProductRouteWithChildren
  '/human/hobbies': typeof HumanHobbiesRoute
  '/human/music': typeof HumanMusicRoute
  '/product/cv': typeof ProductCvRoute
  '/human/': typeof HumanIndexRoute
  '/product/': typeof ProductIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/human'
    | '/product'
    | '/human/hobbies'
    | '/human/music'
    | '/product/cv'
    | '/human/'
    | '/product/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/human/hobbies'
    | '/human/music'
    | '/product/cv'
    | '/human'
    | '/product'
  id:
    | '__root__'
    | '/'
    | '/human'
    | '/product'
    | '/human/hobbies'
    | '/human/music'
    | '/product/cv'
    | '/human/'
    | '/product/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HumanRoute: typeof HumanRouteWithChildren
  ProductRoute: typeof ProductRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/product': {
      id: '/product'
      path: '/product'
      fullPath: '/product'
      preLoaderRoute: typeof ProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/human': {
      id: '/human'
      path: '/human'
      fullPath: '/human'
      preLoaderRoute: typeof HumanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/': {
      id: '/product/'
      path: '/'
      fullPath: '/product/'
      preLoaderRoute: typeof ProductIndexRouteImport
      parentRoute: typeof ProductRoute
    }
    '/human/': {
      id: '/human/'
      path: '/'
      fullPath: '/human/'
      preLoaderRoute: typeof HumanIndexRouteImport
      parentRoute: typeof HumanRoute
    }
    '/product/cv': {
      id: '/product/cv'
      path: '/cv'
      fullPath: '/product/cv'
      preLoaderRoute: typeof ProductCvRouteImport
      parentRoute: typeof ProductRoute
    }
    '/human/music': {
      id: '/human/music'
      path: '/music'
      fullPath: '/human/music'
      preLoaderRoute: typeof HumanMusicRouteImport
      parentRoute: typeof HumanRoute
    }
    '/human/hobbies': {
      id: '/human/hobbies'
      path: '/hobbies'
      fullPath: '/human/hobbies'
      preLoaderRoute: typeof HumanHobbiesRouteImport
      parentRoute: typeof HumanRoute
    }
  }
}

interface HumanRouteChildren {
  HumanHobbiesRoute: typeof HumanHobbiesRoute
  HumanMusicRoute: typeof HumanMusicRoute
  HumanIndexRoute: typeof HumanIndexRoute
}

const HumanRouteChildren: HumanRouteChildren = {
  HumanHobbiesRoute: HumanHobbiesRoute,
  HumanMusicRoute: HumanMusicRoute,
  HumanIndexRoute: HumanIndexRoute,
}

const HumanRouteWithChildren = HumanRoute._addFileChildren(HumanRouteChildren)

interface ProductRouteChildren {
  ProductCvRoute: typeof ProductCvRoute
  ProductIndexRoute: typeof ProductIndexRoute
}

const ProductRouteChildren: ProductRouteChildren = {
  ProductCvRoute: ProductCvRoute,
  ProductIndexRoute: ProductIndexRoute,
}

const ProductRouteWithChildren =
  ProductRoute._addFileChildren(ProductRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HumanRoute: HumanRouteWithChildren,
  ProductRoute: ProductRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
